// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioApps;

#nullable disable

namespace PortfolioApps.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231229022328_Data1")]
    partial class Data1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElementoReaccion", b =>
                {
                    b.Property<int>("ElementoId")
                        .HasColumnType("int");

                    b.Property<int>("ReaccionesId")
                        .HasColumnType("int");

                    b.HasKey("ElementoId", "ReaccionesId");

                    b.HasIndex("ReaccionesId");

                    b.ToTable("ElementoReaccion");

                    b.HasData(
                        new
                        {
                            ElementoId = 3,
                            ReaccionesId = 1
                        },
                        new
                        {
                            ElementoId = 3,
                            ReaccionesId = 3
                        },
                        new
                        {
                            ElementoId = 3,
                            ReaccionesId = 6
                        },
                        new
                        {
                            ElementoId = 3,
                            ReaccionesId = 7
                        },
                        new
                        {
                            ElementoId = 3,
                            ReaccionesId = 8
                        });
                });

            modelBuilder.Entity("PortfolioApps.Entidades.Elemento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Especial")
                        .HasColumnType("bit");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NroAtomico")
                        .HasColumnType("int");

                    b.Property<int>("Posicion")
                        .HasColumnType("int");

                    b.Property<string>("Prefijo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValenciaM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValenciaNM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wiki")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.ToTable("Elementos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Especial = false,
                            GrupoId = 5,
                            Nombre = "Hidrógeno",
                            NroAtomico = 1,
                            Posicion = 1,
                            Simbolo = "H",
                            ValenciaM = "[]",
                            ValenciaNM = "[]",
                            Wiki = "Hidrógeno"
                        },
                        new
                        {
                            Id = 2,
                            Especial = false,
                            GrupoId = 8,
                            Nombre = "Helio",
                            NroAtomico = 2,
                            Posicion = 18,
                            Simbolo = "He",
                            ValenciaM = "[]",
                            ValenciaNM = "[]",
                            Wiki = "Helio"
                        },
                        new
                        {
                            Id = 3,
                            Especial = false,
                            GrupoId = 1,
                            Nombre = "Litio",
                            NroAtomico = 3,
                            Posicion = 19,
                            Simbolo = "Li",
                            ValenciaM = "[1]",
                            ValenciaNM = "[]",
                            Wiki = "Litio"
                        },
                        new
                        {
                            Id = 4,
                            Especial = false,
                            GrupoId = 2,
                            Nombre = "Berilio",
                            NroAtomico = 4,
                            Posicion = 20,
                            Simbolo = "Be",
                            ValenciaM = "[2]",
                            ValenciaNM = "[]",
                            Wiki = "Berilio"
                        },
                        new
                        {
                            Id = 5,
                            Especial = false,
                            GrupoId = 6,
                            Nombre = "Boro",
                            NroAtomico = 5,
                            Posicion = 31,
                            Prefijo = "bor",
                            Simbolo = "B",
                            ValenciaM = "[]",
                            ValenciaNM = "[3]",
                            Wiki = "Boro"
                        },
                        new
                        {
                            Id = 6,
                            Especial = false,
                            GrupoId = 5,
                            Nombre = "Carbono",
                            NroAtomico = 6,
                            Posicion = 32,
                            Prefijo = "carbon",
                            Simbolo = "C",
                            ValenciaM = "[]",
                            ValenciaNM = "[2,4]",
                            Wiki = "Carbono"
                        },
                        new
                        {
                            Id = 7,
                            Especial = false,
                            GrupoId = 5,
                            Nombre = "Nitrógeno",
                            NroAtomico = 7,
                            Posicion = 33,
                            Prefijo = "nitr",
                            Simbolo = "N",
                            ValenciaM = "[]",
                            ValenciaNM = "[3,5]",
                            Wiki = "Nitrógeno"
                        },
                        new
                        {
                            Id = 8,
                            Especial = false,
                            GrupoId = 5,
                            Nombre = "Oxígeno",
                            NroAtomico = 8,
                            Posicion = 34,
                            Simbolo = "O",
                            ValenciaM = "[]",
                            ValenciaNM = "[]",
                            Wiki = "Oxígeno"
                        },
                        new
                        {
                            Id = 9,
                            Especial = false,
                            GrupoId = 5,
                            Nombre = "Flúor",
                            NroAtomico = 9,
                            Posicion = 35,
                            Prefijo = "fluor",
                            Simbolo = "F",
                            ValenciaM = "[]",
                            ValenciaNM = "[1]",
                            Wiki = "Flúor"
                        },
                        new
                        {
                            Id = 10,
                            Especial = false,
                            GrupoId = 8,
                            Nombre = "Neón",
                            NroAtomico = 10,
                            Posicion = 36,
                            Simbolo = "Ne",
                            ValenciaM = "[]",
                            ValenciaNM = "[]",
                            Wiki = "Neón"
                        });
                });

            modelBuilder.Entity("PortfolioApps.Entidades.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grupos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Metal alcalino"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Metal alcalinotérreo"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Metal transicional"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Metal postransicional"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "No metal reactivo"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Metaloides"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Halógeno"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Gas noble"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Lantánido"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Actínido"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Desconocido"
                        });
                });

            modelBuilder.Entity("PortfolioApps.Entidades.Reaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reacciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Óxido metálico"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Óxido no metálico"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Hidróxido"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Ácido"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Hidrácido"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Hidruro metálico"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Sal"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Sal de hidrácido"
                        });
                });

            modelBuilder.Entity("ElementoReaccion", b =>
                {
                    b.HasOne("PortfolioApps.Entidades.Elemento", null)
                        .WithMany()
                        .HasForeignKey("ElementoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortfolioApps.Entidades.Reaccion", null)
                        .WithMany()
                        .HasForeignKey("ReaccionesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortfolioApps.Entidades.Elemento", b =>
                {
                    b.HasOne("PortfolioApps.Entidades.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });
#pragma warning restore 612, 618
        }
    }
}
